Review chapter "Define an application protocol"
heig-vd-dai-course/heig-vd-dai-course pull request #312
Opened 2024-09-26 12:52 UTC by ludelafo

2024-09-27 06:05 UTC, hadrylouis requested changes

2024-09-27 06:05 UTC, hadrylouis commented on 11-define-an-application-protocol/README.md
> +  -->
Just out of curiosity, do you plan to use BeeQuiz this semester ?

2024-09-27 06:05 UTC, hadrylouis commented on 11-define-an-application-protocol/COURSE_MATERIAL.md
>  exchange information between them (usually a between a client and a server). It
Typo : `usually between a client and a server`

2024-09-27 06:05 UTC, hadrylouis commented on 11-define-an-application-protocol/COURSE_MATERIAL.md
> +- `25565`: Minecraft
Love this one :)

2024-09-27 06:05 UTC, hadrylouis commented on 11-define-an-application-protocol/COURSE_MATERIAL.md
> +specific room. The server will respond with the temperature of the room.
I like this exercise as it involves 3 participants

2024-10-03 13:16 UTC, ludelafo commented on 11-define-an-application-protocol/README.md
> +  -->
Not this year as I don't have the time to polish/maintain it to the level needed for it to be truly useful (at least, not these weeks, maybe before the end of the semester).

2024-10-05 15:29 UTC, hadrylouis approved these changes

2024-10-06 11:00 UTC, merged