Review chapter "Java TCP programming"
heig-vd-dai-course/heig-vd-dai-course pull request #375
Opened 2024-10-03 15:17 UTC by ludelafo

2024-10-18 13:41 UTC, hadrylouis requested changes

2024-10-18 13:41 UTC, hadrylouis commented on 12-java-tcp-programming/COURSE_MATERIAL.md
> +section.
I think it's a good thing to no longer ask the students to create a Github discussion, but simply to create one if needed.

2024-10-18 13:41 UTC, hadrylouis commented on 12-java-tcp-programming/COURSE_MATERIAL.md
> +```
Remove this

2024-10-18 16:33 UTC, ludelafo commented on 12-java-tcp-programming/COURSE_MATERIAL.md
> +```
Fixed! Thanks.

2024-10-21 12:53 UTC, ludelafo commented
@hadrylouis, @GeraudSilvestri, I have created the template for this chapter (https://github.com/heig-vd-dai-course/heig-vd-dai-course-java-tcp-programming-practical-content-template). For me, the chapter is complete.

2024-10-28 06:44 UTC, hadrylouis approved these changes

2024-10-28 06:56 UTC, merged