Review chapter "Caching and performance"
heig-vd-dai-course/heig-vd-dai-course pull request #523
Opened 2024-11-29 14:40 UTC by ludelafo

2024-12-09 07:34 UTC, hadrylouis requested changes

2024-12-09 07:34 UTC, hadrylouis commented on 23-caching-and-performance/COURSE_MATERIAL.md
> +can return a `412 Precondition Failed` response to the client.
Just above you mentioned that if the data had changed, we would receive a 200 OK and not a 412.

2024-12-09 07:34 UTC, hadrylouis commented on 23-caching-and-performance/COURSE_MATERIAL.md
Perhaps I'll add the terms “cache HIT” and “cache MISS” somewhere in this document, as it seems to me that this is a term we often see in the context of caches.

2024-12-09 07:34 UTC, hadrylouis commented on 23-caching-and-performance/PRESENTATION.md
> +We are arriving at the end of the second part of the course.
third part of the course

2024-12-13 15:49 UTC, ludelafo commented on 23-caching-and-performance/COURSE_MATERIAL.md
> +can return a `412 Precondition Failed` response to the client.
I have rephrased this to better explain how it works. It should be better now!

2024-12-13 15:50 UTC, ludelafo commented on 23-caching-and-performance/COURSE_MATERIAL.md
I have added a Tip about these terms, good catch (the diagrams were already using _"cache hit"_/_"cache miss"_ so now it's even more clear).

2024-12-13 15:50 UTC, ludelafo commented on 23-caching-and-performance/PRESENTATION.md
> +We are arriving at the end of the second part of the course.
Thanks!

2024-12-13 15:50 UTC, merged